language: cpp
compiler: gcc
sudo: require
dist: trusty

before_install:
    - # sudo add-apt-repository ppa:beineri/opt-qt58-trusty -y
    - # sudo apt-get update -qq
    
install: 
    - sudo apt-get -y install gfortran python3 python3-dev python3-pyqt5 python3-pyqt5.qtopengl python3-pyqt5.qtquick python3-pyqt5.qtsvg python3-numpy python3-serial python3-opengl python3-setuptools qml-module-qtquick2 qml-module-qtquick-window2 qml-module-qtquick-layouts qml-module-qtquick-dialogs qml-module-qtquick-controls gfortran pkg-config libxcb1-dev libx11-dev
    - # source /opt/qt58/bin/qt58-env.sh
    - git clone http://github.com/Ultimaker/cura-build.git
    - cd cura-build
    - mkdir build
    - cd build
    - cmake ..
    - make
    - make package
    - find .
